### ISSUE TITLE
Detailed Design Report

### ISSUE THREAD

**Issue by yagizyasar** [Cargobot-Project/cargobot#14]
### Sections of the Report

- [x] 1. Introduction  
  - [x]   1.1 Purpose of the system  
  - [x]   1.2 Design goals (Usability, Performance, Reliability, Marketability, Extendibility, Security, Scalability, Maintabilty, Flexibility, Modularity, Aesthetics, etc)
  - [x]   1.3 Definitions, acronyms, and abbreviations  
  - [x]   1.4 Overview  
- [x] 2. Current software architecture (competitors, alternative and current solutions, if any)  
- [x] 3. Proposed software architecture  
  - [x]   3.1 Overview   
  - [x]   3.2 Subsystem decomposition
  - [x]   3.3 Models
- [x] 4. Subsystem services
- [x] 5. Test Cases (functional and non functional test cases, procedures and expected results)   
- [x] 6. Consideration of Various Factors in Engineering Design  
- [x] 7. Teamwork Details  
  - [x]   7.1 Contributing and functioning effectively on the team  
  - [x]   7.2 Helping creating a collaborative and inclusive environment   
  - [x]   7.3 Taking lead role and sharing leadership on the team  
- [x] 8. Glossary  
- [x] 9. References

**Comment by yagizyasar** [comment]
-> Part 1, 2, and 6 - from previous documentations
-> Part 3.2 - @KutayDemiray, @berkeucar 
-> Part 3.3 - @gokberkbeydemir 
-> Part 4 - @yagizyasar
-> Part 5 - TBD
-> Part 7 - @saitcanbaskol

**Comment by KutayDemiray** [comment]
#4 will be helpful in section 3 (and possibly 4)

**Comment by yagizyasar** [comment]
Google Docs:
https://docs.google.com/document/d/1P1zj1ITxauv77PzLT2e9NLjSgJBZvLpjbE1orPDttX0/edit
