### ISSUE TITLE
Random Image Generation from Pickup Area

### ISSUE THREAD

**Issue by berkeucar** [Cargobot-Project/cargobot#2]
Prerequirements: #5 and #6

We need to automatically generate many camera images from the Meshcat scene with labels that can be used for a segmentation PyTorch model.

## Features
- [x] Random box configuration
- [x] Plain image generation
- [x] Label image generation
- [ ] Generating with 5 cameras (currently 3)

**Comment by KutayDemiray** [comment]
For random generation, we drop objects from a height, which might rarely result in some weird poses. The optimizer below finds poses that are already in static equilibrium, this may be useful in the future.

https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_static_equilibrium_problem.html
