### ISSUE TITLE
Overall environment design 

### ISSUE THREAD

**Issue by berkeucar** [Cargobot-Project/cargobot#4]
We should design the generic scene beforehand for the generation of the different cluster of boxes photos.

The system diagram can be found [at this file](https://github.com/Cargobot-Project/cargobot/blob/master/docs/SystemDiagram.drawio). Use [draw.io](https://app.diagrams.net/) to open it.

**Comment by KutayDemiray** [comment]
Commit 1d841bf adds a general skeleton of the structure as well as a more detailed perception module.
